/* 016.c COPYRIGHT FUJITSU LIMITED 2017 */
#include "test_mck.h"
#include "testsuite.h"

SETUP_EMPTY(TEST_SUITE, TEST_NUMBER)

RUN_ALIAS(TEST_SUITE, TEST_NUMBER, 0)

TEARDOWN_EMPTY(TEST_SUITE, TEST_NUMBER)

